[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure" 