services:
  - type: web
    name: snackee-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: snackee-db
          property: connectionString

  - type: web
    name: snackee-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: REACT_APP_API_URL
        value: https://snackee-backend.onrender.com
      - key: NODE_ENV
        value: production

databases:
  - name: snackee-db
    databaseName: order_page_db
    ipAllowList: [] 